# dla dev config file

system: dev
base_url: dev-dla.com
base_dir: /home/dlink/dla
data_dir: /data/dla
backup_dir: /data/backups/db
admin_emails: dvlink@gmail.com

database:
   description: David Link Art Dev
   engine: mysql
   host  : localhost
   db    : dla
   user  : dlink
   passwd: $DDB_PASS

logging:
   filename: /var/log/dla/dev_dla.log
   level: DEBUG